apiVersion: apps/v1
kind: Deployment
metadata:
  name: browsepy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: browsepy
  template:
    metadata:

      labels:
        app: browsepy
    spec:
      containers:
        - name: browsepy
          image: browsepy
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - "gunicorn"
            - "browsepy:app"
          ports:
            - containerPort: 8000
